.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml

Templates for
1. Bug report
2. Feature request (ticket)

feat: add templates for tasks and bug reports bb-30

---

apps/frontend/src/assets/css/variables.css

###Summary
Added CSS color variables to variables.css
###Notes
Im not sure about implementations of gradients. Would be nice to have some way to put gradient start and end color into a variable and then specify direction in other css files when needed. Something like a [SASS mixin](https://sass-lang.com/guide/#mixins).

feat: added color variables to varibles.css bb-52

---

apps/backend/src/libs/plugins/authorization-plugin/libs/helpers/check-is-white-route.helper.ts

It seems the Auth Plugin still blocks frontend routes. I hope this PR will fix it.

fix(backend): fix conflicted protected routes bb-11

---

apps/backend/src/libs/plugins/authorization-plugin/libs/helpers/check-is-white-route.helper.ts
package-lock.json

Another bug fixes 🙃
Already tested on localhost, even on the online TS playground😭

fix(backend): fix invalid regex on white route helper bb-11

---

apps/backend/src/modules/users/user.repository.ts

fix(backend): Authenticated user endpoint fails to return information about the user bb-137

---

apps/frontend/src/pages/auth/components/sign-in-form/sign-in-form.tsx

fix(frontend): different case in sign in bb-150

---

apps/backend/package.json
apps/backend/src/modules/auth/auth.controller.ts
apps/backend/src/modules/users/user.controller.ts
package-lock.json

Regarding issue #155, it turns out that the problem is only with the documentation. Hope this PR resolves it.

fix(backend): add missing auth docs for `/users` endpoint bb-155

---

apps/frontend/src/pages/quiz/libs/components/introduction/styles.module.css

Updated breakpoint on quiz introduction screen

fix: update breakpoint on quiz introduction screen bb-199

---

apps/frontend/src/index.tsx

Quiz component was wrapped into protected route
- index.ts

fix(frontend): wrap quiz component into protected route bb-234

---

apps/mobile/src/screens/auth/auth.tsx
apps/mobile/src/screens/tasks/tasks.tsx
apps/mobile/src/slices/auth/actions.ts
package-lock.json

Fixed issue 219 where an error message appeared after tapping on the 'Create an account' link. The issue has been resolved to prevent the error message from displaying.
https://github.com/user-attachments/assets/05d21a02-947a-41c1-9b31-a0979b2fd8ff

fix(mobile): an error message appears after tap on "create an account" link bb-219

---

apps/frontend/src/libs/components/progress-bar/styles.module.css
apps/frontend/src/libs/components/protected-route/libs/constants/routes-without-auth-wrapper.constant.ts
apps/frontend/src/pages/onboarding/libs/components/onboarding-answer/styles.module.css
apps/frontend/src/pages/onboarding/onboarding.tsx
apps/frontend/src/pages/onboarding/styles.module.css

https://github.com/user-attachments/assets/cb585684-01b9-46b8-bb11-fd0519769f37

feat: Onboarding questions screen mobile responsiveness bb-289

---

apps/frontend/src/libs/components/input/input.tsx
apps/frontend/src/libs/components/input/styles.module.css

Fixed extra spaces between label and field
- input.tsx
- styles for input

fix(frontend): fix extra spaces between label and field bb-312

---

apps/frontend/src/pages/not-found/not-found.tsx

Changed text on not found page

feat(frontend): change the text on not found page bb-278

---

apps/frontend/src/libs/components/loader/loader.tsx
apps/frontend/src/libs/components/loader/styles.module.css

Added new text for a loader component
- loader.tsx
- styles.module.css for loader

feat(frontend): add new text for a loader component bb-243

---

apps/mobile/src/packages/users/libs/types/types.ts
apps/mobile/src/packages/users/users-api.ts
apps/mobile/src/packages/users/users.ts
apps/mobile/src/screens/tasks/tasks.tsx
apps/mobile/src/slices/users/actions.ts
apps/mobile/src/slices/users/users.slice.ts
apps/mobile/src/slices/users/users.ts

Fixed an error message that appears when an authorized user taps on the "Tasks" button.
[task_fix.webm](https://github.com/user-attachments/assets/3bf941bd-d0d7-4f0c-b076-7addabb02ee5)

fix(mobile): error message appear authorized user tap on "Tasks" bb-350

---

apps/frontend/src/libs/components/checkbox/styles.module.css
packages/shared/src/modules/users/libs/enums/user-validation-message.enum.ts
packages/shared/src/modules/users/libs/validation-schemas/notification-answers-validation-schema.ts

- Add max length for task days
- Add rule for unique days value

fix(shared): notification questions validation bb-243

---

apps/backend/src/modules/users/user.service.ts

Remove password data fron responce

fix(backend): return UserDto on saveNotificationAnswers bb-243

---

apps/frontend/src/pages/onboarding/styles.module.css

fix(frontend): Change the appearance of Next and Back buttons for the web version bb-400

---

apps/mobile/src/libs/components/background-wrapper/background-wrapper.tsx
apps/mobile/src/libs/components/background-wrapper/libs/maps/maps.ts
apps/mobile/src/libs/components/background-wrapper/libs/maps/preset-to-planet-position-map.ts
apps/mobile/src/libs/components/background-wrapper/libs/maps/preset-to-planet-position.map.ts
apps/mobile/src/libs/components/background-wrapper/styles.ts
apps/mobile/src/libs/components/planet/libs/maps/maps.ts
apps/mobile/src/libs/components/planet/planet.tsx
apps/mobile/src/libs/components/planet/styles.ts
apps/mobile/src/libs/components/tag/tag.tsx
apps/mobile/src/libs/maps/maps.ts
apps/mobile/src/libs/maps/size-to-styles/size-to-styles.ts
apps/mobile/src/screens/auth/auth.tsx
apps/mobile/src/screens/welcome/welcome.tsx
apps/mobile/src/screens/wheel-loading/wheel-loading.tsx

feat(mobile): background component bb-154

---

apps/frontend/src/libs/components/link/styles.module.css

fix(frontend): incorrect color of sidebar buttons bb-406

---

apps/mobile/src/libs/enums/navigation/root-screen-name.enum.ts
apps/mobile/src/libs/types/navigation/root-navigation-parameter-list.type.ts
apps/mobile/src/navigations/root/root.tsx
apps/mobile/src/packages/users/libs/enums/enums.ts
apps/mobile/src/packages/users/libs/types/types.ts
apps/mobile/src/packages/users/libs/validation-schemas/validation-schemas.ts
apps/mobile/src/packages/users/users-api.ts
apps/mobile/src/packages/users/users.ts
apps/mobile/src/screens/notification-questions/libs/components/components.ts
apps/mobile/src/screens/notification-questions/libs/components/notification-frequency/notification-frequency-question.tsx
apps/mobile/src/screens/notification-questions/libs/components/notification-frequency/styles.ts
apps/mobile/src/screens/notification-questions/libs/components/notification-task-days/notification-task-days.tsx
apps/mobile/src/screens/notification-questions/libs/components/notification-task-days/styles.ts
apps/mobile/src/screens/notification-questions/libs/constants/constants.ts
apps/mobile/src/screens/notification-questions/libs/constants/notification-questions-form-default-values.constant.ts
apps/mobile/src/screens/notification-questions/libs/constants/notification-questions-options.constant.ts
apps/mobile/src/screens/notification-questions/libs/types/notification-questions-form-values.type.ts
apps/mobile/src/screens/notification-questions/libs/types/root-stack-parameter-list.type.ts
apps/mobile/src/screens/notification-questions/libs/types/types.ts
apps/mobile/src/screens/notification-questions/notification-questions.tsx
apps/mobile/src/screens/notification-questions/styles.ts
apps/mobile/src/screens/quiz/quiz.tsx
apps/mobile/src/slices/users/actions.ts
apps/mobile/src/slices/users/users.slice.ts
apps/mobile/src/slices/users/users.ts

- Add a separate screen with a form for the last questions.
- Created a form that contains checkboxes for days of week selection and two radio buttons.
- Save data when the user clicks save and redirects to the Wheel Loading screen.
[preview-last-questions.webm](https://github.com/user-attachments/assets/5a224464-9f22-41f2-8cc3-aa43f558438e)

feat(mobile): last step quiz questions bb-330

---

apps/mobile/src/screens/auth/components/sign-in-form/sign-in-form.tsx
apps/mobile/src/screens/auth/components/sign-up-form/sign-up-form.tsx

**Summary**
Changed Sign In link "to" property value to the right one.**
**Screenshots**
https://github.com/user-attachments/assets/77927b0e-e1c8-42ba-882d-89784e906a2e

fix(mobile): Sign in" link on the "Create an account" page is inactive bb-461

---

apps/frontend/src/libs/components/checkbox/checkbox.tsx
apps/frontend/src/libs/components/checkbox/styles.module.css
apps/frontend/src/pages/quiz/libs/components/notification-questions/libs/constants/notification-questions-form-default-values.constant.ts
apps/frontend/src/pages/quiz/libs/components/notification-questions/notification-questions.tsx

- Added quick tip after question
- Changed default answer

feat(frontend): add default answer and quick tip bb-460

---

apps/mobile/src/libs/components/wheel/libs/helpers/get-sector-parameters/get-sector-parameters.helper.ts
apps/mobile/src/navigations/root/root.tsx
apps/mobile/src/screens/notification-questions/notification-questions.tsx
apps/mobile/src/screens/onboarding/onboarding.tsx
apps/mobile/src/screens/tasks/tasks.tsx

Fixed issues according to the description in [issue](https://github.com/BinaryStudioAcademy/bsa-2024-bebalance/issues/480#issue-2532971747)
The issue with INPUT_ICON_SIZE was fixed before.

refactor(mobile): fix issues with quality criterias bb-480

---

apps/frontend/src/libs/components/link/link.tsx
apps/frontend/src/libs/components/link/styles.module.css
package-lock.json

Related to issue #371, this PR will add a hover design on the Sidebar Navigation Items.
https://github.com/user-attachments/assets/57848ffd-b18a-467a-a494-50b536660759

feat(frontend): add hover design on sidebar nav item bb-371

---

apps/frontend/src/libs/components/balance-wheel-chart/libs/constants/wheel-chart-config.constant.ts

- fix balance wheel truncated border when animating.

fix(frontend): Balance Wheel animation bb-204

---

apps/frontend/src/pages/auth/auth.tsx

#483 Updated redirection after sign up.

fix(frontend): incorrect redirection after account creation attempt with existing email bb-483

---

apps/frontend/src/pages/profile/profile.tsx

- added the close icon to the Sign Out popup

feat(frontend): add close icon bb-487
